/// Shared option lists for the auth signup forms, matching the enums the
/// backend's Joi validators (`CreateUserRequest`, `CreateSpotOwnerRequest`)
/// accept. Values here must stay in sync with those enums or registration
/// requests will fail validation.
const List<String> nigerianStates = [
  'Abia',
  'Adamawa',
  'Akwa Ibom',
  'Anambra',
  'Bauchi',
  'Bayelsa',
  'Benue',
  'Borno',
  'Cross River',
  'Delta',
  'Ebonyi',
  'Edo',
  'Ekiti',
  'Enugu',
  'FCT',
  'Gombe',
  'Imo',
  'Jigawa',
  'Kaduna',
  'Kano',
  'Katsina',
  'Kebbi',
  'Kogi',
  'Kwara',
  'Lagos',
  'Nasarawa',
  'Niger',
  'Ogun',
  'Ondo',
  'Osun',
  'Oyo',
  'Plateau',
  'Rivers',
  'Sokoto',
  'Taraba',
  'Yobe',
  'Zamfara',
];

const List<String> heardAboutUsOptions = [
  'Facebook',
  'Instagram',
  'TikTok',
  'Twitter/X',
  'Google Search',
  'YouTube',
  'Friend',
  'Family',
  'Referral',
  'Advertisement',
  'Other',
];
